apiVersion: v1
kind: ServiceAccount
metadata:
  name: intelligent-backoffice-api
  namespace: intelligent-backoffice
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: intelligent-backoffice-workers
  namespace: intelligent-backoffice
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: intelligent-backoffice-document-intelligence
  namespace: intelligent-backoffice
automountServiceAccountToken: false
